INSERT INTO TODO (ID, NAME, DESC, IS_DONE, DATE_COMPLETION)
VALUES(1001, 'DK', 'Complete Spring boot Course', false, CURRENT_DATE());



INSERT INTO TODO (ID, NAME, DESC, IS_DONE, DATE_COMPLETION)
VALUES(1002, 'DK', 'Complete Spring boot Course', false, CURRENT_DATE());

INSERT INTO TODO (ID, NAME, DESC, IS_DONE, DATE_COMPLETION)
VALUES(1003, 'DKODE', 'Complete Spring boot Course', false, CURRENT_DATE());

INSERT INTO TODO (ID, NAME, DESC, IS_DONE, DATE_COMPLETION)
VALUES(1004, 'DK', 'Complete Spring boot Course', false, CURRENT_DATE());

INSERT INTO TODO (ID, NAME, DESC, IS_DONE, DATE_COMPLETION)
VALUES(1005, 'DK', 'Complete Spring boot Course', false, CURRENT_DATE());

INSERT INTO TODO (ID, NAME, DESC, IS_DONE, DATE_COMPLETION)
VALUES(1006, 'DK', 'Complete Spring boot Course', false, CURRENT_DATE());